### ISSUE TITLE
@angular/cli throws ngcc error when building v2.3.1

### ISSUE THREAD

**Issue by dpraul** [dhilt/ngx-ui-scroll#299]
I am running Angular 12.2.13. When I try to update to ngx-ui-scroll 2.3.1, I get the following error at build-time:

<details>
<summary>Build stacktrace</summary>

```
Error: Error on worker #1: Error: Failed to find exported name of node (UiScrollComponent = /** @class */ (function () {
        function UiScrollComponent(changeDetector, elementRef) {
            this.changeDetector = changeDetector;
            this.elementRef = elementRef;
            // the only template variable
            this.items = [];
        }
        UiScrollComponent.prototype.ngOnInit = function () {
            var _this = this;
            this.workflow = new Workflow({
                consumer: consumer,
                element: this.elementRef.nativeElement,
                datasource: this.datasource,
                run: function (items) {
                    if (!items.length && !_this.items.length) {
                        return;
                    }
                    _this.items = items;
                    _this.changeDetector.detectChanges();
                }
            });
        };
        UiScrollComponent.prototype.ngOnDestroy = function () {
            this.workflow.dispose();
        };
        UiScrollComponent.decorators = [
            { type: core$1.Component, args: [{
                        selector: '[ui-scroll]',
                        changeDetection: core$1.ChangeDetectionStrategy.OnPush,
                        template: "\n    <div data-padding-backward></div>\n    <div\n      *ngFor=\"let item of items\"\n      [attr.data-sid]=\"item.$index\"\n      [style.position]=\"item.invisible ? 'fixed' : null\"\n      [style.left]=\"item.invisible ? '-99999px' : null\">\n      <ng-template\n        [ngTemplateOutlet]=\"template\"\n        [ngTemplateOutletContext]=\"{\n          $implicit: item.data,\n          index: item.$index,\n          odd: item.$index % 2,\n          even: !(item.$index % 2)\n      }\"></ng-template>\n    </div>\n    <div data-padding-forward></div>"
                    },] }
        ];
        UiScrollComponent.ctorParameters = function () { return [
            { type: core$1.ChangeDetectorRef },
            { type: core$1.ElementRef }
        ]; };
        return UiScrollComponent;
    }())) in '/build/node_modules/ngx-ui-scroll/bundles/ngx-ui-scroll.umd.js'.
    at Object.findExportedNameOfNode (/build/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/find_export.js:56:19)
    at LogicalProjectStrategy.emit (/build/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:256:38)
    at ReferenceEmitter.emit (/build/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:72:44)
    at Object.toR3Reference (/build/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:247:18)
    at NgModuleDecoratorHandler._toR3Reference (/build/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:535:31)
    at /build/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:265:83
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (/build/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:265:48)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (/build/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:421:40)
    at analyze (/build/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:371:58)
    at ClusterMaster.onWorkerMessage (/build/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:195:27)
    at /build/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:55:95
    at ClusterMaster.<anonymous> (/build/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:293:57)
    at step (/build/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:143:27)
    at Object.next (/build/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:124:57)
    at /build/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/build/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:113:16)
    at EventEmitter.<anonymous> (/build/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:287:32)
    at EventEmitter.emit (node:events:390:28)
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^
Error: write EPIPE
    at process.target._send (node:internal/child_process:846:20)
    at process.target.send (node:internal/child_process:719:19)
    at /build/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:51:21
    at new Promise (<anonymous>)
    at Object.sendMessageToMaster (/build/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:46:16)
    at /build/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:104:66
    at step (/build/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/build/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:124:57)
    at rejected (/build/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
[webpack-cli] Error: NGCC failed.
    at NgccProcessor.process (/build/node_modules/@ngtools/webpack/src/ngcc_processor.js:139:19)
    at /build/node_modules/@ngtools/webpack/src/ivy/plugin.js:129:27
    at Hook.eval [as call] (eval at create (/build/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:1)
    at Hook.CALL_DELEGATE [as _call] (/build/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/build/node_modules/webpack/lib/Compiler.js:1043:30)
    at /build/node_modules/webpack/lib/Compiler.js:1088:29
    at Hook.eval [as callAsync] (eval at create (/build/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/build/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/build/node_modules/webpack/lib/Compiler.js:1083:28)
    at /build/node_modules/webpack/lib/Compiler.js:508:12
error Command failed with exit code 2.
```

</details>

**Comment by dhilt** [comment]
@dpraul The build looks broken. It might be an environment specific issue, so I need more details. In my environments I don't experience it: 

 - https://dhilt.github.io/ngx-ui-scroll/#/ works with ngx-ui-scroll 2.3.1 and Angular 12.2.13
 - compiling and running the same stack locally don't meet any issues

My demo app build works with the following config on my end:

https://github.com/dhilt/ngx-ui-scroll/blob/2517ffbbe488a2a29d76450e2c7edc6bb3ca4e5b/angular.json#L36-L51

Could you extend the log and make it started from npm-build command? and attach your build configuration?
